/* Generated By:JJTree: Do not edit this line. ASTdelete_array_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.fzi.sim.kascpar.sc2ast;

public
class ASTdelete_array_expression extends SimpleNode {
  public ASTdelete_array_expression(int id) {
    super(id);
  }

  public ASTdelete_array_expression(SCParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SCParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=23e23a3720fec416144e251d19867200 (do not edit this line) */
