/* Generated By:JJTree&JavaCC: Do not edit this line. SCParserConstants.java */
package de.fzi.sim.kascpar.sc2ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LCURLYBRACE = 17;
  /** RegularExpression Id. */
  int RCURLYBRACE = 18;
  /** RegularExpression Id. */
  int LSQUAREBRACKET = 19;
  /** RegularExpression Id. */
  int RSQUAREBRACKET = 20;
  /** RegularExpression Id. */
  int LPARENTHESIS = 21;
  /** RegularExpression Id. */
  int RPARENTHESIS = 22;
  /** RegularExpression Id. */
  int SCOPE = 23;
  /** RegularExpression Id. */
  int COLON = 24;
  /** RegularExpression Id. */
  int SEMICOLON = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int QUESTIONMARK = 27;
  /** RegularExpression Id. */
  int ELLIPSIS = 28;
  /** RegularExpression Id. */
  int ASSIGNEQUAL = 29;
  /** RegularExpression Id. */
  int TIMESEQUAL = 30;
  /** RegularExpression Id. */
  int DIVIDEEQUAL = 31;
  /** RegularExpression Id. */
  int MODEQUAL = 32;
  /** RegularExpression Id. */
  int PLUSEQUAL = 33;
  /** RegularExpression Id. */
  int MINUSEQUAL = 34;
  /** RegularExpression Id. */
  int SHIFTLEFTEQUAL = 35;
  /** RegularExpression Id. */
  int SHIFTRIGHTEQUAL = 36;
  /** RegularExpression Id. */
  int BITWISEANDEQUAL = 37;
  /** RegularExpression Id. */
  int BITWISEXOREQUAL = 38;
  /** RegularExpression Id. */
  int BITWISEOREQUAL = 39;
  /** RegularExpression Id. */
  int OR = 40;
  /** RegularExpression Id. */
  int AND = 41;
  /** RegularExpression Id. */
  int BITWISEOR = 42;
  /** RegularExpression Id. */
  int BITWISEXOR = 43;
  /** RegularExpression Id. */
  int AMPERSAND = 44;
  /** RegularExpression Id. */
  int EQUAL = 45;
  /** RegularExpression Id. */
  int NOTEQUAL = 46;
  /** RegularExpression Id. */
  int LESSTHAN = 47;
  /** RegularExpression Id. */
  int GREATERTHAN = 48;
  /** RegularExpression Id. */
  int LESSTHANOREQUALTO = 49;
  /** RegularExpression Id. */
  int GREATERTHANOREQUALTO = 50;
  /** RegularExpression Id. */
  int SHIFTLEFT = 51;
  /** RegularExpression Id. */
  int SHIFTRIGHT = 52;
  /** RegularExpression Id. */
  int PLUS = 53;
  /** RegularExpression Id. */
  int MINUS = 54;
  /** RegularExpression Id. */
  int STAR = 55;
  /** RegularExpression Id. */
  int DIVIDE = 56;
  /** RegularExpression Id. */
  int MOD = 57;
  /** RegularExpression Id. */
  int PLUSPLUS = 58;
  /** RegularExpression Id. */
  int MINUSMINUS = 59;
  /** RegularExpression Id. */
  int TILDE = 60;
  /** RegularExpression Id. */
  int NOT = 61;
  /** RegularExpression Id. */
  int DOT = 62;
  /** RegularExpression Id. */
  int POINTERTO = 63;
  /** RegularExpression Id. */
  int DOTSTAR = 64;
  /** RegularExpression Id. */
  int ARROWSTAR = 65;
  /** RegularExpression Id. */
  int AUTO = 66;
  /** RegularExpression Id. */
  int BREAK = 67;
  /** RegularExpression Id. */
  int CASE = 68;
  /** RegularExpression Id. */
  int CATCH = 69;
  /** RegularExpression Id. */
  int CHAR = 70;
  /** RegularExpression Id. */
  int CONST = 71;
  /** RegularExpression Id. */
  int CONTINUE = 72;
  /** RegularExpression Id. */
  int _DEFAULT = 73;
  /** RegularExpression Id. */
  int DELETE = 74;
  /** RegularExpression Id. */
  int DO = 75;
  /** RegularExpression Id. */
  int DOUBLE = 76;
  /** RegularExpression Id. */
  int ELSE = 77;
  /** RegularExpression Id. */
  int ENUM = 78;
  /** RegularExpression Id. */
  int EXTERN = 79;
  /** RegularExpression Id. */
  int FLOAT = 80;
  /** RegularExpression Id. */
  int FOR = 81;
  /** RegularExpression Id. */
  int FRIEND = 82;
  /** RegularExpression Id. */
  int GOTO = 83;
  /** RegularExpression Id. */
  int IF = 84;
  /** RegularExpression Id. */
  int INLINE = 85;
  /** RegularExpression Id. */
  int EXPLICIT = 86;
  /** RegularExpression Id. */
  int INT = 87;
  /** RegularExpression Id. */
  int UINT64 = 88;
  /** RegularExpression Id. */
  int LONG = 89;
  /** RegularExpression Id. */
  int NEW = 90;
  /** RegularExpression Id. */
  int PRIVATE = 91;
  /** RegularExpression Id. */
  int PROTECTED = 92;
  /** RegularExpression Id. */
  int PUBLIC = 93;
  /** RegularExpression Id. */
  int REDECLARED = 94;
  /** RegularExpression Id. */
  int REGISTER = 95;
  /** RegularExpression Id. */
  int RETURN = 96;
  /** RegularExpression Id. */
  int SHORT = 97;
  /** RegularExpression Id. */
  int SIGNED = 98;
  /** RegularExpression Id. */
  int SIZEOF = 99;
  /** RegularExpression Id. */
  int STATIC = 100;
  /** RegularExpression Id. */
  int STRUCT = 101;
  /** RegularExpression Id. */
  int CLASS = 102;
  /** RegularExpression Id. */
  int SWITCH = 103;
  /** RegularExpression Id. */
  int TEMPLATE = 104;
  /** RegularExpression Id. */
  int THIS = 105;
  /** RegularExpression Id. */
  int TRY = 106;
  /** RegularExpression Id. */
  int TYPEDEF = 107;
  /** RegularExpression Id. */
  int UNION = 108;
  /** RegularExpression Id. */
  int UNSIGNED = 109;
  /** RegularExpression Id. */
  int VIRTUAL = 110;
  /** RegularExpression Id. */
  int VOID = 111;
  /** RegularExpression Id. */
  int VOLATILE = 112;
  /** RegularExpression Id. */
  int WHILE = 113;
  /** RegularExpression Id. */
  int OPERATOR = 114;
  /** RegularExpression Id. */
  int TRUETOK = 115;
  /** RegularExpression Id. */
  int FALSETOK = 116;
  /** RegularExpression Id. */
  int BOOL = 117;
  /** RegularExpression Id. */
  int THROW = 118;
  /** RegularExpression Id. */
  int NAMESPACE = 119;
  /** RegularExpression Id. */
  int USING = 120;
  /** RegularExpression Id. */
  int TYPENAME = 121;
  /** RegularExpression Id. */
  int SC_MODULE_MACRO = 122;
  /** RegularExpression Id. */
  int SC_MODULE = 123;
  /** RegularExpression Id. */
  int SC_CHANNEL = 124;
  /** RegularExpression Id. */
  int SC_BEHAVIOR = 125;
  /** RegularExpression Id. */
  int SC_CTOR = 126;
  /** RegularExpression Id. */
  int SC_INT = 127;
  /** RegularExpression Id. */
  int SC_UINT = 128;
  /** RegularExpression Id. */
  int SC_BIGINT = 129;
  /** RegularExpression Id. */
  int SC_BIGUINT = 130;
  /** RegularExpression Id. */
  int SC_IN = 131;
  /** RegularExpression Id. */
  int SC_OUT = 132;
  /** RegularExpression Id. */
  int SC_INOUT = 133;
  /** RegularExpression Id. */
  int SENSITIVE = 134;
  /** RegularExpression Id. */
  int SENSITIVE_POS = 135;
  /** RegularExpression Id. */
  int SENSITIVE_NEG = 136;
  /** RegularExpression Id. */
  int SC_THREAD = 137;
  /** RegularExpression Id. */
  int SC_CTHREAD = 138;
  /** RegularExpression Id. */
  int SC_EVENT = 139;
  /** RegularExpression Id. */
  int SC_EVENT_LIST = 140;
  /** RegularExpression Id. */
  int SC_EVENT_OR_LIST = 141;
  /** RegularExpression Id. */
  int SC_EVENT_AND_LIST = 142;
  /** RegularExpression Id. */
  int SC_METHOD = 143;
  /** RegularExpression Id. */
  int SC_BIT = 144;
  /** RegularExpression Id. */
  int SC_BIT_VECTOR = 145;
  /** RegularExpression Id. */
  int SC_LOGIC = 146;
  /** RegularExpression Id. */
  int SC_LOGIC_VECTOR = 147;
  /** RegularExpression Id. */
  int SC_LOGIC_VECTOR_BASE = 148;
  /** RegularExpression Id. */
  int SC_PROXY = 149;
  /** RegularExpression Id. */
  int SC_WITHOUT_CONTEXT = 150;
  /** RegularExpression Id. */
  int SC_GLOBAL = 151;
  /** RegularExpression Id. */
  int SC_BITREF_R = 152;
  /** RegularExpression Id. */
  int SC_BITREF = 153;
  /** RegularExpression Id. */
  int SC_SUBREF_R = 154;
  /** RegularExpression Id. */
  int SC_SUBREF = 155;
  /** RegularExpression Id. */
  int SC_CONCREF_R = 156;
  /** RegularExpression Id. */
  int SC_CONCREF = 157;
  /** RegularExpression Id. */
  int SC_FIXED = 158;
  /** RegularExpression Id. */
  int SC_UFIXED = 159;
  /** RegularExpression Id. */
  int SC_FIX = 160;
  /** RegularExpression Id. */
  int SC_UFIX = 161;
  /** RegularExpression Id. */
  int SC_FXNUM = 162;
  /** RegularExpression Id. */
  int SC_FIXED_FAST = 163;
  /** RegularExpression Id. */
  int SC_UFIXED_FAST = 164;
  /** RegularExpression Id. */
  int SC_FXNUM_FAST = 165;
  /** RegularExpression Id. */
  int SC_FMT = 166;
  /** RegularExpression Id. */
  int SC_NUMREP = 167;
  /** RegularExpression Id. */
  int SC_FIX_FAST = 168;
  /** RegularExpression Id. */
  int SC_UFIX_FAST = 169;
  /** RegularExpression Id. */
  int SC_FXTYPE_PARAMS = 170;
  /** RegularExpression Id. */
  int SC_FXTYPE_CONTEXT = 171;
  /** RegularExpression Id. */
  int SC_FXCAST_SWITCH = 172;
  /** RegularExpression Id. */
  int SC_FXCAST_CONTEXT = 173;
  /** RegularExpression Id. */
  int SC_FXNUM_BITREF = 174;
  /** RegularExpression Id. */
  int SC_FXNUM_FAST_BITREF = 175;
  /** RegularExpression Id. */
  int SC_FXNUM_SUBREF = 176;
  /** RegularExpression Id. */
  int SC_FXNUM_FAST_SUBREF = 177;
  /** RegularExpression Id. */
  int SCFX_IEEE_DOUBLE = 178;
  /** RegularExpression Id. */
  int SCFX_IEEE_FLOAT = 179;
  /** RegularExpression Id. */
  int SCFX_MANT = 180;
  /** RegularExpression Id. */
  int SCFX_MANT_REF = 181;
  /** RegularExpression Id. */
  int SCFX_PARAMS = 182;
  /** RegularExpression Id. */
  int SCFX_INDEX = 183;
  /** RegularExpression Id. */
  int SCFX_REP = 184;
  /** RegularExpression Id. */
  int SCFX_STRING = 185;
  /** RegularExpression Id. */
  int SCFX_INT_BITREF_R = 186;
  /** RegularExpression Id. */
  int SCFX_INT_BITREF = 187;
  /** RegularExpression Id. */
  int SCFX_INT_SUBREF_R = 188;
  /** RegularExpression Id. */
  int SCFX_INT_SUBREF = 189;
  /** RegularExpression Id. */
  int SC_LENGTH_PARAM = 190;
  /** RegularExpression Id. */
  int SC_SIGNED_BITREF_R = 191;
  /** RegularExpression Id. */
  int SC_SIGNED_BITREF = 192;
  /** RegularExpression Id. */
  int SC_SIGNED_SUBREF_R = 193;
  /** RegularExpression Id. */
  int SC_SIGNED_SUBREF = 194;
  /** RegularExpression Id. */
  int SC_UINT_BITREF_R = 195;
  /** RegularExpression Id. */
  int SC_UINT_BITREF = 196;
  /** RegularExpression Id. */
  int SC_UINT_SUBREF_R = 197;
  /** RegularExpression Id. */
  int SC_UINT_SUBREF = 198;
  /** RegularExpression Id. */
  int SC_UNSIGNED_BITREF_R = 199;
  /** RegularExpression Id. */
  int SC_UNSIGNED_BITREF = 200;
  /** RegularExpression Id. */
  int SC_UNSIGNED_SUBREF_R = 201;
  /** RegularExpression Id. */
  int SC_UNSIGNED_SUBREF = 202;
  /** RegularExpression Id. */
  int SC_CONCATREF = 203;
  /** RegularExpression Id. */
  int SC_CONCAT_BOOL = 204;
  /** RegularExpression Id. */
  int SC_VALUE_BASE = 205;
  /** RegularExpression Id. */
  int SC_GENERIC_BASE = 206;
  /** RegularExpression Id. */
  int SC_SIGNAL = 207;
  /** RegularExpression Id. */
  int SC_BUFFER = 208;
  /** RegularExpression Id. */
  int SC_WATCH = 209;
  /** RegularExpression Id. */
  int SC_EXPORT_BASE = 210;
  /** RegularExpression Id. */
  int SC_PORT_BASE = 211;
  /** RegularExpression Id. */
  int SC_PORT_REGISTRY = 212;
  /** RegularExpression Id. */
  int SC_PORT_B = 213;
  /** RegularExpression Id. */
  int SC_PORT = 214;
  /** RegularExpression Id. */
  int SC_INTERFACE = 215;
  /** RegularExpression Id. */
  int SC_MUTEX_IF = 216;
  /** RegularExpression Id. */
  int SC_SEMAPHORE_IF = 217;
  /** RegularExpression Id. */
  int SC_MUTEX = 218;
  /** RegularExpression Id. */
  int SC_SEMAPHORE = 219;
  /** RegularExpression Id. */
  int SC_SIGNAL_IN_IF = 220;
  /** RegularExpression Id. */
  int SC_SIGNAL_OUT_IF = 221;
  /** RegularExpression Id. */
  int SC_SIGNAL_INOUT_IF = 222;
  /** RegularExpression Id. */
  int SC_IN_CLK = 223;
  /** RegularExpression Id. */
  int SC_OUT_CLK = 224;
  /** RegularExpression Id. */
  int SC_INOUT_CLK = 225;
  /** RegularExpression Id. */
  int SC_IN_RESOLVED = 226;
  /** RegularExpression Id. */
  int SC_OUT_RESOLVED = 227;
  /** RegularExpression Id. */
  int SC_INOUT_RESOLVED = 228;
  /** RegularExpression Id. */
  int SC_LV_RESOLVE = 229;
  /** RegularExpression Id. */
  int SC_IN_RV = 230;
  /** RegularExpression Id. */
  int SC_OUT_RV = 231;
  /** RegularExpression Id. */
  int SC_INOUT_RV = 232;
  /** RegularExpression Id. */
  int SC_FIFO_IN = 233;
  /** RegularExpression Id. */
  int SC_FIFO_OUT = 234;
  /** RegularExpression Id. */
  int SC_SIGNAL_RESOLVED = 235;
  /** RegularExpression Id. */
  int SC_SIGNAL_RV = 236;
  /** RegularExpression Id. */
  int SC_CLOCK = 237;
  /** RegularExpression Id. */
  int SC_TIME = 238;
  /** RegularExpression Id. */
  int SC_JOIN = 239;
  /** RegularExpression Id. */
  int SC_LAMBDA = 240;
  /** RegularExpression Id. */
  int SC_TIME_PARAMS = 241;
  /** RegularExpression Id. */
  int SC_CURR_PROC_INFO = 242;
  /** RegularExpression Id. */
  int SC_MSG_DEF = 243;
  /** RegularExpression Id. */
  int SC_TRACE_PARAMS = 244;
  /** RegularExpression Id. */
  int SC_BIND_PROXY = 245;
  /** RegularExpression Id. */
  int SC_LAMBDA_RATOR_E = 246;
  /** RegularExpression Id. */
  int SC_LAMBDA_RAND_E = 247;
  /** RegularExpression Id. */
  int SC_ENC = 248;
  /** RegularExpression Id. */
  int SC_LAMBDA_PTR = 249;
  /** RegularExpression Id. */
  int SC_LAMBDA_RAND = 250;
  /** RegularExpression Id. */
  int SC_CTHREAD_HANDLE = 251;
  /** RegularExpression Id. */
  int SC_METHOD_HANDLE = 252;
  /** RegularExpression Id. */
  int SC_THREAD_HANDLE = 253;
  /** RegularExpression Id. */
  int SC_PROCESS_CB = 254;
  /** RegularExpression Id. */
  int SC_PROCESS_CALL = 255;
  /** RegularExpression Id. */
  int SC_EVENT_TIMED = 256;
  /** RegularExpression Id. */
  int SC_ZERO_TIME = 257;
  /** RegularExpression Id. */
  int SC_WAIT_ROUTINE = 258;
  /** RegularExpression Id. */
  int SC_WAIT_UNTIL_ROUTINE = 259;
  /** RegularExpression Id. */
  int SC_WATCHING_ROUTINE = 260;
  /** RegularExpression Id. */
  int SC_NEXT_TRIGGER = 261;
  /** RegularExpression Id. */
  int SC_NOTIFY = 262;
  /** RegularExpression Id. */
  int SC_LOGIC_RESOLVE = 263;
  /** RegularExpression Id. */
  int SC_ASSERT = 264;
  /** RegularExpression Id. */
  int SC_CONTEXT = 265;
  /** RegularExpression Id. */
  int SC_CONTEXT_BEGIN = 266;
  /** RegularExpression Id. */
  int SC_SWITCH = 267;
  /** RegularExpression Id. */
  int SC_MODULE_NAME = 268;
  /** RegularExpression Id. */
  int SC_CYCLE = 269;
  /** RegularExpression Id. */
  int SC_INITIALIZE = 270;
  /** RegularExpression Id. */
  int SC_FIFO = 271;
  /** RegularExpression Id. */
  int SC_FIFO_NB_IN_IF = 272;
  /** RegularExpression Id. */
  int SC_FIFO_B_IN_IF = 273;
  /** RegularExpression Id. */
  int SC_FIFO_NB_OUT_IF = 274;
  /** RegularExpression Id. */
  int SC_FIFO_B_OUT_IF = 275;
  /** RegularExpression Id. */
  int SC_FIFO_IN_IF = 276;
  /** RegularExpression Id. */
  int SC_FIFO_OUT_IF = 277;
  /** RegularExpression Id. */
  int SC_HAS_PROCESS = 278;
  /** RegularExpression Id. */
  int SC_MAIN = 279;
  /** RegularExpression Id. */
  int SC_MASTER = 280;
  /** RegularExpression Id. */
  int SC_INMASTER = 281;
  /** RegularExpression Id. */
  int SC_INOUTMASTER = 282;
  /** RegularExpression Id. */
  int SC_OUTMASTER = 283;
  /** RegularExpression Id. */
  int SC_SLAVE = 284;
  /** RegularExpression Id. */
  int SC_INSLAVE = 285;
  /** RegularExpression Id. */
  int SC_INOUTSLAVE = 286;
  /** RegularExpression Id. */
  int SC_OUTSLAVE = 287;
  /** RegularExpression Id. */
  int SC_NOHANDSHAKE = 288;
  /** RegularExpression Id. */
  int SC_ENABLEHANDSHAKE = 289;
  /** RegularExpression Id. */
  int SC_FULLHANDSHAKE = 290;
  /** RegularExpression Id. */
  int SC_INDEXED = 291;
  /** RegularExpression Id. */
  int SC_O_MODE = 292;
  /** RegularExpression Id. */
  int SC_OBJECT = 293;
  /** RegularExpression Id. */
  int SC_PROCESS_BASE = 294;
  /** RegularExpression Id. */
  int SC_SPAWN_OBJECT = 295;
  /** RegularExpression Id. */
  int SC_SPAWN_OBJECT_V = 296;
  /** RegularExpression Id. */
  int SC_PROCESS_HOST = 297;
  /** RegularExpression Id. */
  int SC_PROCESS_MONITOR = 298;
  /** RegularExpression Id. */
  int SC_RUNNABLE = 299;
  /** RegularExpression Id. */
  int SC_CLK_POS_CALLBACK = 300;
  /** RegularExpression Id. */
  int SC_CLK_NEG_CALLBACK = 301;
  /** RegularExpression Id. */
  int SC_CHECK = 302;
  /** RegularExpression Id. */
  int SC_PRIM_CHANNEL = 303;
  /** RegularExpression Id. */
  int SC_PRIM_CHANNEL_REG = 304;
  /** RegularExpression Id. */
  int SC_PROTOCOL_MACRO = 305;
  /** RegularExpression Id. */
  int SC_Q_MODE = 306;
  /** RegularExpression Id. */
  int SC_SET_TIME_RESOLUTION = 307;
  /** RegularExpression Id. */
  int SC_GET_TIME_RESOLUTION = 308;
  /** RegularExpression Id. */
  int SC_SET_DEFAULT_TIME_UNIT = 309;
  /** RegularExpression Id. */
  int SC_GET_DEFAULT_TIME_UNIT = 310;
  /** RegularExpression Id. */
  int SC_SLAVE_MACRO = 311;
  /** RegularExpression Id. */
  int SC_STOP = 312;
  /** RegularExpression Id. */
  int SC_STOP_HERE_ROUTINE = 313;
  /** RegularExpression Id. */
  int SC_START = 314;
  /** RegularExpression Id. */
  int SC_STRING = 315;
  /** RegularExpression Id. */
  int DONT_INITIALIZE = 316;
  /** RegularExpression Id. */
  int SC_TIME_UNIT = 317;
  /** RegularExpression Id. */
  int SC_TIME_STAMP = 318;
  /** RegularExpression Id. */
  int SC_TRACE = 319;
  /** RegularExpression Id. */
  int SC_TRACE_FILE = 320;
  /** RegularExpression Id. */
  int VCD_TRACE_FILE = 321;
  /** RegularExpression Id. */
  int WIF_TRACE_FILE = 322;
  /** RegularExpression Id. */
  int ISDB_TRACE_FILE = 323;
  /** RegularExpression Id. */
  int VCD_T_TRACE = 324;
  /** RegularExpression Id. */
  int WIF_T_TRACE = 325;
  /** RegularExpression Id. */
  int SC_PHASH_BASE = 326;
  /** RegularExpression Id. */
  int SC_PHASH_BASE_ITER = 327;
  /** RegularExpression Id. */
  int SC_PHASH = 328;
  /** RegularExpression Id. */
  int SC_PHASH_ITER = 329;
  /** RegularExpression Id. */
  int SC_PDHASH = 330;
  /** RegularExpression Id. */
  int SC_PDHASH_ITER = 331;
  /** RegularExpression Id. */
  int SC_STRHASH = 332;
  /** RegularExpression Id. */
  int SC_STRHASH_ITER = 333;
  /** RegularExpression Id. */
  int SC_PLIST_BASE = 334;
  /** RegularExpression Id. */
  int SC_PLIST_BASE_ITER = 335;
  /** RegularExpression Id. */
  int SC_MEMPOOL = 336;
  /** RegularExpression Id. */
  int SC_MPOBJECT = 337;
  /** RegularExpression Id. */
  int SC_PPQ = 338;
  /** RegularExpression Id. */
  int SC_PPQ_BASE = 339;
  /** RegularExpression Id. */
  int SC_CREATE_VCD_TRACE_FILE = 340;
  /** RegularExpression Id. */
  int SC_CLOSE_VCD_TRACE_FILE = 341;
  /** RegularExpression Id. */
  int SC_CREATE_WIF_TRACE_FILE = 342;
  /** RegularExpression Id. */
  int SC_CLOSE_WIF_TRACE_FILE = 343;
  /** RegularExpression Id. */
  int SC_CREATE_ISDB_TRACE_FILE = 344;
  /** RegularExpression Id. */
  int SC_CLOSE_ISDB_TRACE_FILE = 345;
  /** RegularExpression Id. */
  int W_BEGIN = 346;
  /** RegularExpression Id. */
  int W_DO = 347;
  /** RegularExpression Id. */
  int W_ESCAPE = 348;
  /** RegularExpression Id. */
  int W_END = 349;
  /** RegularExpression Id. */
  int SC_SPAWN_OPTIONS = 350;
  /** RegularExpression Id. */
  int SC_PROCESS_HANDLE = 351;
  /** RegularExpression Id. */
  int SC_FORK_MACRO = 352;
  /** RegularExpression Id. */
  int SC_JOIN_MACRO = 353;
  /** RegularExpression Id. */
  int SC_SPAWN_ROUTINE = 354;
  /** RegularExpression Id. */
  int SC_BIND_ROUTINE = 355;
  /** RegularExpression Id. */
  int SC_REF_ROUTINE = 356;
  /** RegularExpression Id. */
  int SC_CREF_ROUTINE = 357;
  /** RegularExpression Id. */
  int SC_EVENT_QUEUE = 358;
  /** RegularExpression Id. */
  int SC_EXPORT = 359;
  /** RegularExpression Id. */
  int SC_EXPORT_REGISTRY = 360;
  /** RegularExpression Id. */
  int SC_SEVERITY = 361;
  /** RegularExpression Id. */
  int SC_ACTION = 362;
  /** RegularExpression Id. */
  int SC_ACTIONS = 363;
  /** RegularExpression Id. */
  int SC_REPORT = 364;
  /** RegularExpression Id. */
  int SC_REPORT_HANDLER = 365;
  /** RegularExpression Id. */
  int SC_REPORT_INFO_MACRO = 366;
  /** RegularExpression Id. */
  int SC_REPORT_WARNING_MACRO = 367;
  /** RegularExpression Id. */
  int SC_REPORT_ERROR_MACRO = 368;
  /** RegularExpression Id. */
  int SC_REPORT_FATAL_MACRO = 369;
  /** RegularExpression Id. */
  int SC_STRING_OLD = 370;
  /** RegularExpression Id. */
  int SC_BYTE_HEAP = 371;
  /** RegularExpression Id. */
  int SC_VPOOL = 372;
  /** RegularExpression Id. */
  int SC_MAIN_MAIN_ROUTINE = 373;
  /** RegularExpression Id. */
  int SC_ARGC_ROUTINE = 374;
  /** RegularExpression Id. */
  int SC_ARGV_ROUTINE = 375;
  /** RegularExpression Id. */
  int SC_START_OF_SIMULATION_INVOKED_ROUTINE = 376;
  /** RegularExpression Id. */
  int SC_END_OF_SIMULATION_INVOKED_ROUTINE = 377;
  /** RegularExpression Id. */
  int SC_STOP_MODE = 378;
  /** RegularExpression Id. */
  int SC_SET_STOP_MODE_ROUTINE = 379;
  /** RegularExpression Id. */
  int SC_GEN_UNIQUE_NAME_ROUTINE = 380;
  /** RegularExpression Id. */
  int SC_SIMCONTEXT = 381;
  /** RegularExpression Id. */
  int SC_API_VERSION_STRING = 382;
  /** RegularExpression Id. */
  int SC_COR = 383;
  /** RegularExpression Id. */
  int SC_COR_PKG = 384;
  /** RegularExpression Id. */
  int SC_METHOD_PROCESS = 385;
  /** RegularExpression Id. */
  int SC_SIMULATION_TIME_ROUTINE = 386;
  /** RegularExpression Id. */
  int SC_GET_CURR_PROCESS_HANDLE_ROUTINE = 387;
  /** RegularExpression Id. */
  int SC_GET_CURR_SIMCONTEXT_ROUTINE = 388;
  /** RegularExpression Id. */
  int SC_PROCESS_B = 389;
  /** RegularExpression Id. */
  int SC_CURR_PROC_KIND = 390;
  /** RegularExpression Id. */
  int SC_GET_LAST_CREATED_PROCESS_HANDLE_ROUTINE = 391;
  /** RegularExpression Id. */
  int SC_GET_CURR_PROCESS_KIND_ROUTINE = 392;
  /** RegularExpression Id. */
  int SC_MAP_TO_TARGET_INIT_MACRO = 393;
  /** RegularExpression Id. */
  int SC_MAP_TO_TARGET_MACRO = 394;
  /** RegularExpression Id. */
  int SC_SENSITIVE = 395;
  /** RegularExpression Id. */
  int SC_SENSITIVE_POS = 396;
  /** RegularExpression Id. */
  int SC_SENSITIVE_NEG = 397;
  /** RegularExpression Id. */
  int SC_COPYRIGHT_ROUTINE = 398;
  /** RegularExpression Id. */
  int SC_VERSION_ROUTINE = 399;
  /** RegularExpression Id. */
  int SC_ABS_ROUTINE = 400;
  /** RegularExpression Id. */
  int SC_MAX_ROUTINE = 401;
  /** RegularExpression Id. */
  int SC_MIN_ROUTINE = 402;
  /** RegularExpression Id. */
  int SC_LOGIC_VALUE_T = 403;
  /** RegularExpression Id. */
  int SC_MAX_NUM_DELTA_CYCLES = 404;
  /** RegularExpression Id. */
  int SC_ATTR_BASE = 405;
  /** RegularExpression Id. */
  int SC_ATTRIBUTE = 406;
  /** RegularExpression Id. */
  int SC_ATTR_CLTN = 407;
  /** RegularExpression Id. */
  int SC_BV_BASE = 408;
  /** RegularExpression Id. */
  int SC_EVENT_FINDER_T = 409;
  /** RegularExpression Id. */
  int SC_EVENT_FINDER = 410;
  /** RegularExpression Id. */
  int SC_EVENT_QUEUE_IF = 411;
  /** RegularExpression Id. */
  int SC_FXNUM_FAST_OBSERVER = 412;
  /** RegularExpression Id. */
  int SC_FXNUM_OBSERVER = 413;
  /** RegularExpression Id. */
  int SC_FXVAL = 414;
  /** RegularExpression Id. */
  int SC_FXVAL_FAST = 415;
  /** RegularExpression Id. */
  int SC_FXVAL_FAST_OBSERVER = 416;
  /** RegularExpression Id. */
  int SC_FXVAL_OBSERVER = 417;
  /** RegularExpression Id. */
  int SC_INT_BASE = 418;
  /** RegularExpression Id. */
  int SC_LENGTH_CONTEXT = 419;
  /** RegularExpression Id. */
  int SC_PVECTOR = 420;
  /** RegularExpression Id. */
  int SC_UINT_BASE = 421;
  /** RegularExpression Id. */
  int SC_UNSIGNED = 422;
  /** RegularExpression Id. */
  int SC_SIGNED = 423;
  /** RegularExpression Id. */
  int SC_PLIST_ITER = 424;
  /** RegularExpression Id. */
  int SC_PLIST = 425;
  /** RegularExpression Id. */
  int COUT = 426;
  /** RegularExpression Id. */
  int CERR = 427;
  /** RegularExpression Id. */
  int TLM_SYNC_ENUM = 428;
  /** RegularExpression Id. */
  int TLM_INITIATOR_SOCKET = 429;
  /** RegularExpression Id. */
  int TLM_TARGET_SOCKET = 430;
  /** RegularExpression Id. */
  int PEQ_WITH_CB_AND_PHASE = 431;
  /** RegularExpression Id. */
  int TLM_DMI = 432;
  /** RegularExpression Id. */
  int OCTALINT = 433;
  /** RegularExpression Id. */
  int OCTALLONG = 434;
  /** RegularExpression Id. */
  int UNSIGNED_OCTALINT = 435;
  /** RegularExpression Id. */
  int UNSIGNED_OCTALLONG = 436;
  /** RegularExpression Id. */
  int DECIMALINT = 437;
  /** RegularExpression Id. */
  int DECIMALLONG = 438;
  /** RegularExpression Id. */
  int UNSIGNED_DECIMALINT = 439;
  /** RegularExpression Id. */
  int UNSIGNED_DECIMALLONG = 440;
  /** RegularExpression Id. */
  int HEXADECIMALINT = 441;
  /** RegularExpression Id. */
  int HEXADECIMALLONG = 442;
  /** RegularExpression Id. */
  int UNSIGNED_HEXADECIMALINT = 443;
  /** RegularExpression Id. */
  int UNSIGNED_HEXADECIMALLONG = 444;
  /** RegularExpression Id. */
  int FLOATONE = 445;
  /** RegularExpression Id. */
  int FLOATTWO = 446;
  /** RegularExpression Id. */
  int FIXED_POINT_QUANTIZATION_TYPE = 447;
  /** RegularExpression Id. */
  int FIXED_POINT_OVERFLOW_TYPE = 448;
  /** RegularExpression Id. */
  int SC_TIME_CONSTANTS = 449;
  /** RegularExpression Id. */
  int SC_CONTEXT_BEGIN_CONSTANTS = 450;
  /** RegularExpression Id. */
  int SC_SWITCH_CONSTANTS = 451;
  /** RegularExpression Id. */
  int SC_FMT_CONSTANTS = 452;
  /** RegularExpression Id. */
  int SC_NUMREP_CONSTANTS = 453;
  /** RegularExpression Id. */
  int SC_LAMBDA_RAND_E_CONSTANTS = 454;
  /** RegularExpression Id. */
  int SC_ENC_CONSTANTS = 455;
  /** RegularExpression Id. */
  int SC_SEVERITY_CONSTANTS = 456;
  /** RegularExpression Id. */
  int SC_ACTION_CONSTANTS = 457;
  /** RegularExpression Id. */
  int SC_REPORT_HANDLER_METHODS = 458;
  /** RegularExpression Id. */
  int SC_STOP_MODE_CONSTANTS = 459;
  /** RegularExpression Id. */
  int SC_CURR_PROC_KIND_CONSTANTS = 460;
  /** RegularExpression Id. */
  int SC_IO_MANIPULATORS = 461;
  /** RegularExpression Id. */
  int SC_IO_MANIPULATOR_WITH_PARAM = 462;
  /** RegularExpression Id. */
  int SC_LOGIC_VALUE_T_CONSTANT = 463;
  /** RegularExpression Id. */
  int SC_LOGIC_CONSTANT = 464;
  /** RegularExpression Id. */
  int CHARACTER = 465;
  /** RegularExpression Id. */
  int STRING = 466;
  /** RegularExpression Id. */
  int PREPROCESSOR_OUTPUT = 467;
  /** RegularExpression Id. */
  int FZI_SIM_PRAGMA = 468;
  /** RegularExpression Id. */
  int FZI_SIM_PRAGMA_ITER_TYPE = 469;
  /** RegularExpression Id. */
  int FZI_SIM_PRAGMA_SIGNAL_TYPE = 470;
  /** RegularExpression Id. */
  int ID = 473;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int LINE_NUMBER = 1;
  /** Lexical state. */
  int LINE_DIRECTIVE = 2;
  /** Lexical state. */
  int AFTER_LINE_DIRECTIVE = 3;
  /** Lexical state. */
  int IN_LINE_COMMENT = 4;
  /** Lexical state. */
  int IN_COMMENT = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"\\n\"",
    "\" \"",
    "\"\\t\"",
    "\"//\"",
    "\"/*\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "<token of kind 9>",
    "\"\\n\"",
    "<token of kind 11>",
    "<token of kind 12>",
    "\"\\n\"",
    "<token of kind 14>",
    "\"*/\"",
    "<token of kind 16>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"::\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"?\"",
    "\"...\"",
    "\"=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"!\"",
    "\".\"",
    "\"->\"",
    "\".*\"",
    "\"->*\"",
    "\"auto\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"delete\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extern\"",
    "\"float\"",
    "\"for\"",
    "\"friend\"",
    "\"goto\"",
    "\"if\"",
    "\"inline\"",
    "\"explicit\"",
    "\"int\"",
    "\"uint64\"",
    "\"long\"",
    "\"new\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"redeclared\"",
    "\"register\"",
    "\"return\"",
    "\"short\"",
    "\"signed\"",
    "\"sizeof\"",
    "\"static\"",
    "\"struct\"",
    "\"class\"",
    "\"switch\"",
    "\"template\"",
    "\"this\"",
    "\"try\"",
    "\"typedef\"",
    "\"union\"",
    "\"unsigned\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"operator\"",
    "\"true\"",
    "\"false\"",
    "\"bool\"",
    "\"throw\"",
    "\"namespace\"",
    "\"using\"",
    "\"typename\"",
    "\"SC_MODULE\"",
    "\"sc_module\"",
    "\"sc_channel\"",
    "\"sc_behavior\"",
    "\"SC_CTOR\"",
    "\"sc_int\"",
    "\"sc_uint\"",
    "\"sc_bigint\"",
    "\"sc_biguint\"",
    "\"sc_in\"",
    "\"sc_out\"",
    "\"sc_inout\"",
    "\"sensitive\"",
    "\"sensitive_pos\"",
    "\"sensitive_neg\"",
    "\"SC_THREAD\"",
    "\"SC_CTHREAD\"",
    "\"sc_event\"",
    "\"sc_event_list\"",
    "\"sc_event_or_list\"",
    "\"sc_event_and_list\"",
    "\"SC_METHOD\"",
    "\"sc_bit\"",
    "\"sc_bv\"",
    "\"sc_logic\"",
    "\"sc_lv\"",
    "\"sc_lv_base\"",
    "\"sc_proxy\"",
    "\"sc_without_context\"",
    "\"sc_global\"",
    "\"sc_bitref_r\"",
    "\"sc_bitref\"",
    "\"sc_subref_r\"",
    "\"sc_subref\"",
    "\"sc_concref_r\"",
    "\"sc_concref\"",
    "\"sc_fixed\"",
    "\"sc_ufixed\"",
    "\"sc_fix\"",
    "\"sc_ufix\"",
    "\"sc_fxnum\"",
    "\"sc_fixed_fast\"",
    "\"sc_ufixed_fast\"",
    "\"sc_fxnum_fast\"",
    "\"sc_fmt\"",
    "\"sc_numrep\"",
    "\"sc_fix_fast\"",
    "\"sc_ufix_fast\"",
    "\"sc_fxtype_params\"",
    "\"sc_fxtype_context\"",
    "\"sc_fxcast_switch\"",
    "\"sc_fxcast_context\"",
    "\"sc_fxnum_bitref\"",
    "\"sc_fxnum_fast_bitref\"",
    "\"sc_fxnum_subref\"",
    "\"sc_fxnum_fast_subref\"",
    "\"scfx_ieee_double\"",
    "\"scfx_ieee_float\"",
    "\"scfx_mant\"",
    "\"scfx_mant_ref\"",
    "\"scfx_params\"",
    "\"scfx_index\"",
    "\"scfx_rep\"",
    "\"scfx_string\"",
    "\"sc_int_bitref_r\"",
    "\"sc_int_bitref\"",
    "\"sc_int_subref_r\"",
    "\"sc_int_subref\"",
    "\"sc_length_param\"",
    "\"sc_signed_bitref_r\"",
    "\"sc_signed_bitref\"",
    "\"sc_signed_subref_r\"",
    "\"sc_signed_subref\"",
    "\"sc_uint_bitref_r\"",
    "\"sc_uint_bitref\"",
    "\"sc_uint_subref_r\"",
    "\"sc_uint_subref\"",
    "\"sc_unsigned_bitref_r\"",
    "\"sc_unsigned_bitref\"",
    "\"sc_unsigned_subref_r\"",
    "\"sc_unsigned_subref\"",
    "\"sc_concatref\"",
    "\"sc_concat_bool\"",
    "\"sc_value_base\"",
    "\"sc_generic_base\"",
    "\"sc_signal\"",
    "\"sc_buffer\"",
    "\"sc_watch\"",
    "\"sc_export_base\"",
    "\"sc_port_base\"",
    "\"sc_port_registry\"",
    "\"sc_port_b\"",
    "\"sc_port\"",
    "\"sc_interface\"",
    "\"sc_mutex_if\"",
    "\"sc_semaphore_if\"",
    "\"sc_mutex\"",
    "\"sc_semaphore\"",
    "\"sc_signal_in_if\"",
    "\"sc_signal_out_if\"",
    "\"sc_signal_inout_if\"",
    "\"sc_in_clk\"",
    "\"sc_out_clk\"",
    "\"sc_inout_clk\"",
    "\"sc_in_resolved\"",
    "\"sc_out_resolved\"",
    "\"sc_inout_resolved\"",
    "\"sc_lv_resolve\"",
    "\"sc_in_rv\"",
    "\"sc_out_rv\"",
    "\"sc_inout_rv\"",
    "\"sc_fifo_in\"",
    "\"sc_fifo_out\"",
    "\"sc_signal_resolved\"",
    "\"sc_signal_rv\"",
    "\"sc_clock\"",
    "\"sc_time\"",
    "\"sc_join\"",
    "\"sc_lambda\"",
    "\"sc_time_params\"",
    "\"sc_curr_proc_info\"",
    "\"sc_msg_def\"",
    "\"sc_trace_params\"",
    "\"sc_bind_proxy\"",
    "\"sc_lambda_rator_e\"",
    "\"sc_lambda_rand_e\"",
    "\"sc_enc\"",
    "\"sc_lambda_ptr\"",
    "\"sc_lambda_rand\"",
    "\"sc_cthread_handle\"",
    "\"sc_method_handle\"",
    "\"sc_thread_handle\"",
    "\"sc_process_call_base\"",
    "\"sc_process_call\"",
    "\"sc_event_timed\"",
    "\"SC_ZERO_TIME\"",
    "\"wait\"",
    "\"wait_until\"",
    "\"watching\"",
    "\"next_trigger\"",
    "\"notify\"",
    "\"sc_logic_resolve\"",
    "\"sc_assert\"",
    "\"sc_context\"",
    "\"sc_context_begin\"",
    "\"sc_switch\"",
    "\"sc_module_name\"",
    "\"sc_cycle\"",
    "\"sc_initialize\"",
    "\"sc_fifo\"",
    "\"sc_fifo_nonblocking_in_if\"",
    "\"sc_fifo_blocking_in_if\"",
    "\"sc_fifo_nonblocking_out_if\"",
    "\"sc_fifo_blocking_out_if\"",
    "\"sc_fifo_in_if\"",
    "\"sc_fifo_out_if\"",
    "\"SC_HAS_PROCESS\"",
    "\"sc_main\"",
    "\"sc_master\"",
    "\"sc_inmaster\"",
    "\"sc_inoutmaster\"",
    "\"sc_outmaster\"",
    "\"sc_slave\"",
    "\"sc_inslave\"",
    "\"sc_inoutslave\"",
    "\"sc_outslave\"",
    "\"sc_noHandshake\"",
    "\"sc_enableHandshake\"",
    "\"sc_fullHandshake\"",
    "\"sc_indexed\"",
    "\"sc_o_mode\"",
    "\"sc_object\"",
    "\"sc_process_base\"",
    "\"sc_spawn_object\"",
    "\"sc_spawn_object_v\"",
    "\"sc_process_host\"",
    "\"sc_process_monitor\"",
    "\"sc_runnable\"",
    "\"sc_clock_posedge_callback\"",
    "\"sc_clock_negedge_callback\"",
    "\"sc_check\"",
    "\"sc_prim_channel\"",
    "\"sc_prim_channel_registry\"",
    "\"SC_PROTOCOL\"",
    "\"SC_Q_MODE\"",
    "\"sc_set_time_resolution\"",
    "\"sc_get_time_resolution\"",
    "\"sc_set_default_time_unit\"",
    "\"sc_get_default_time_unit\"",
    "\"SC_SLAVE\"",
    "\"sc_stop\"",
    "\"sc_stop_here\"",
    "\"sc_start\"",
    "\"sc_string\"",
    "\"dont_initialize\"",
    "\"sc_time_unit\"",
    "\"sc_time_stamp\"",
    "\"sc_trace\"",
    "\"sc_trace_file\"",
    "\"vcd_trace_file\"",
    "\"wif_trace_file\"",
    "\"isdb_trace_file\"",
    "\"vcd_T_trace\"",
    "\"wif_T_trace\"",
    "\"sc_phash_base\"",
    "\"sc_phash_base_iter\"",
    "\"sc_phash\"",
    "\"sc_phash_iter\"",
    "\"sc_pdhash\"",
    "\"sc_pdhash_iter\"",
    "\"sc_strhash\"",
    "\"sc_strhash_iter\"",
    "\"sc_plist_base\"",
    "\"sc_plist_base_iter\"",
    "\"sc_mempool\"",
    "\"sc_mpobject\"",
    "\"sc_ppq\"",
    "\"sc_ppq_base\"",
    "\"sc_create_vcd_trace_file\"",
    "\"sc_close_vcd_trace_file\"",
    "\"sc_create_wif_trace_file\"",
    "\"sc_close_wif_trace_file\"",
    "\"sc_create_isdb_trace_file\"",
    "\"sc_close_isdb_trace_file\"",
    "\"W_BEGIN\"",
    "\"W_DO\"",
    "\"W_ESCAPE\"",
    "\"W_END\"",
    "\"sc_spawn_options\"",
    "\"sc_process_handle\"",
    "\"SC_FORK\"",
    "\"SC_JOIN\"",
    "\"sc_spawn\"",
    "\"sc_bind\"",
    "\"sc_ref\"",
    "\"sc_cref\"",
    "\"sc_event_queue\"",
    "\"sc_export\"",
    "\"sc_export_registry\"",
    "\"sc_severity\"",
    "\"sc_action\"",
    "\"sc_actions\"",
    "\"sc_report\"",
    "\"sc_report_handler\"",
    "\"SC_REPORT_INFO\"",
    "\"SC_REPORT_WARNING\"",
    "\"SC_REPORT_ERROR\"",
    "\"SC_REPORT_FATAL\"",
    "\"sc_string_old\"",
    "\"sc_byte_heap\"",
    "\"sc_vpool\"",
    "\"sc_main_main\"",
    "\"sc_argc\"",
    "\"sc_argv\"",
    "\"sc_start_of_simulation_invoked\"",
    "\"sc_end_of_simulation_invoked\"",
    "\"sc_stop_mode\"",
    "\"sc_set_stop_mode\"",
    "\"sc_gen_unique_name\"",
    "\"sc_simcontext\"",
    "\"SC_API_VERSION_STRING\"",
    "\"sc_cor\"",
    "\"sc_cor_pkg\"",
    "\"sc_method_process\"",
    "\"sc_simulation_time\"",
    "\"sc_get_curr_process_handle\"",
    "\"sc_get_curr_simcontext\"",
    "\"sc_process_b\"",
    "\"sc_curr_process_kind\"",
    "\"sc_get_last_created_process_handle\"",
    "\"sc_get_curr_process_kind\"",
    "\"SC_MAP_TO_TARGET_INIT\"",
    "\"SC_MAP_TO_TARGET\"",
    "\"sc_sensitive\"",
    "\"sc_sensitive_pos\"",
    "\"sc_sensitive_neg\"",
    "\"sc_copyright\"",
    "\"sc_version\"",
    "\"sc_abs\"",
    "\"sc_max\"",
    "\"sc_min\"",
    "\"sc_logic_value_t\"",
    "\"SC_MAX_NUM_DELTA_CYCLES\"",
    "\"sc_attr_base\"",
    "\"sc_attribute\"",
    "\"sc_attr_cltn\"",
    "\"sc_bv_base\"",
    "\"sc_event_finder_t\"",
    "\"sc_event_finder\"",
    "\"sc_event_queue_if\"",
    "\"sc_fxnum_fast_observer\"",
    "\"sc_fxnum_observer\"",
    "\"sc_fxval\"",
    "\"sc_fxval_fast\"",
    "\"sc_fxval_fast_observer\"",
    "\"sc_fxval_observer\"",
    "\"sc_int_base\"",
    "\"sc_length_context\"",
    "\"sc_pvector\"",
    "\"sc_uint_base\"",
    "\"sc_unsigned\"",
    "\"sc_signed\"",
    "\"sc_plist_iter\"",
    "\"sc_plist\"",
    "\"cout\"",
    "\"cerr\"",
    "\"tlm_sync_enum\"",
    "\"tlm_initiator_socket\"",
    "\"tlm_target_socket\"",
    "\"peq_with_cb_and_phase\"",
    "\"tlm_dmi\"",
    "<OCTALINT>",
    "<OCTALLONG>",
    "<UNSIGNED_OCTALINT>",
    "<UNSIGNED_OCTALLONG>",
    "<DECIMALINT>",
    "<DECIMALLONG>",
    "<UNSIGNED_DECIMALINT>",
    "<UNSIGNED_DECIMALLONG>",
    "<HEXADECIMALINT>",
    "<HEXADECIMALLONG>",
    "<UNSIGNED_HEXADECIMALINT>",
    "<UNSIGNED_HEXADECIMALLONG>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<FIXED_POINT_QUANTIZATION_TYPE>",
    "<FIXED_POINT_OVERFLOW_TYPE>",
    "<SC_TIME_CONSTANTS>",
    "<SC_CONTEXT_BEGIN_CONSTANTS>",
    "<SC_SWITCH_CONSTANTS>",
    "<SC_FMT_CONSTANTS>",
    "<SC_NUMREP_CONSTANTS>",
    "<SC_LAMBDA_RAND_E_CONSTANTS>",
    "<SC_ENC_CONSTANTS>",
    "<SC_SEVERITY_CONSTANTS>",
    "<SC_ACTION_CONSTANTS>",
    "<SC_REPORT_HANDLER_METHODS>",
    "<SC_STOP_MODE_CONSTANTS>",
    "<SC_CURR_PROC_KIND_CONSTANTS>",
    "<SC_IO_MANIPULATORS>",
    "<SC_IO_MANIPULATOR_WITH_PARAM>",
    "<SC_LOGIC_VALUE_T_CONSTANT>",
    "<SC_LOGIC_CONSTANT>",
    "<CHARACTER>",
    "<STRING>",
    "<PREPROCESSOR_OUTPUT>",
    "\"//pragma_SysXplorer\"",
    "\"iterations\"",
    "\"signal\"",
    "\"\\\\\"",
    "\"finally\"",
    "<ID>",
    "\"`\"",
  };

}
