/* Generated By:JavaCC: Do not edit this line. SCParserTreeConstants.java Version 5.0 */
package de.fzi.sim.kascpar.sc2ast;

public interface SCParserTreeConstants
{
  public int JJTTRANSLATION_UNIT = 0;
  public int JJTVOID = 1;
  public int JJTPREPROCESSOR_DIRECTIVE = 2;
  public int JJTEXTERNAL_DECLARATION = 3;
  public int JJTFZI_SIM_DIRECTIVE = 4;
  public int JJTSC_MAIN_DECLARATION = 5;
  public int JJTBLOCK_STATEMENT = 6;
  public int JJTBLOCK = 7;
  public int JJTSYSTEMCROUTINE = 8;
  public int JJTDYN_PROCESS_CREATION_BLOCK_DECLARATION = 9;
  public int JJTSC_PORT_SPECIFIER = 10;
  public int JJTM_S_PROTOCOL_DECLARATION = 11;
  public int JJTSC_SLAVE = 12;
  public int JJTSC_METHOD = 13;
  public int JJTSC_THREAD = 14;
  public int JJTSC_REPORT_MACRO = 15;
  public int JJTSC_CTHREAD = 16;
  public int JJTSC_WATCHING_LIST = 17;
  public int JJTSC_WATCHING = 18;
  public int JJTSC_SENSITIVE = 19;
  public int JJTPOSTFIX_EXPRESSION = 20;
  public int JJTSC_NOTIFY = 21;
  public int JJTFUNCTION_DEFINITION = 22;
  public int JJTLINKAGE_SPECIFICATION = 23;
  public int JJTDECLARATION = 24;
  public int JJTINIT_DECLARATOR_LIST = 25;
  public int JJTTYPE_MODIFIERS = 26;
  public int JJTDECLARATION_SPECIFIERS = 27;
  public int JJTTYPE_SPECIFIER = 28;
  public int JJTSIMPLE_TYPE_SPECIFIER = 29;
  public int JJTSCOPE_OVERRIDE_LOOKAHEAD = 30;
  public int JJTSCOPE_OVERRIDE = 31;
  public int JJTQUALIFIED_ID = 32;
  public int JJTPTR_TO_MEMBER = 33;
  public int JJTQUALIFIED_TYPE = 34;
  public int JJTTYPE_QUALIFIER = 35;
  public int JJTSTORAGE_CLASS_SPECIFIER = 36;
  public int JJTBUILTIN_TYPE_SPECIFIER = 37;
  public int JJTINIT_DECLARATOR = 38;
  public int JJTCLASS_HEAD = 39;
  public int JJTCLASS_SPECIFIER = 40;
  public int JJTBASE_CLAUSE = 41;
  public int JJTBASE_CLASS_ACCESS_SPECIFIER = 42;
  public int JJTBASE_SPECIFIER = 43;
  public int JJTACCESS_SPECIFIER = 44;
  public int JJTBIT_FIELD_MEMBER_DECLARATION = 45;
  public int JJTMEMBER_DECLARATION = 46;
  public int JJTMEMBER_DECLARATOR_LIST = 47;
  public int JJTMEMBER_DECLARATOR = 48;
  public int JJTCONVERSION_FUNCTION_DECL_OR_DEF = 49;
  public int JJTENUM_SPECIFIER = 50;
  public int JJTENUMERATOR_LIST = 51;
  public int JJTENUMERATOR = 52;
  public int JJTPTR_OPERATOR = 53;
  public int JJTCV_QUALIFIER = 54;
  public int JJTDECLARATOR = 55;
  public int JJTDECLARATOR_SUFFIXES = 56;
  public int JJTFUNCTION_DECLARATOR_LOOKAHEAD = 57;
  public int JJTFUNCTION_DECLARATOR = 58;
  public int JJTDTOR_CTOR_DECL_SPEC = 59;
  public int JJTDTOR_DEFINITION = 60;
  public int JJTLOCAL_WATCHING_BLOCK = 61;
  public int JJTBEGIN_BLOCK = 62;
  public int JJTDO_BLOCK = 63;
  public int JJTESCAPE_BLOCK = 64;
  public int JJTCTOR_DEFINITION = 65;
  public int JJTSC_METHOD_BLOCK = 66;
  public int JJTSC_THREAD_BLOCK = 67;
  public int JJTSC_CTHREAD_BLOCK = 68;
  public int JJTCTOR_DECLARATOR_LOOKAHEAD = 69;
  public int JJTCTOR_INITIALIZER = 70;
  public int JJTSUPERCLASS_INIT = 71;
  public int JJTDTOR_DECLARATOR = 72;
  public int JJTSIMPLE_DTOR_DECLARATOR = 73;
  public int JJTPARAMETER_LIST = 74;
  public int JJTELLIPSIS_PARAMETER = 75;
  public int JJTPARAMETER_DECLARATION = 76;
  public int JJTINITIALIZER = 77;
  public int JJTARRAY_INITIALIZER = 78;
  public int JJTTYPE_NAME = 79;
  public int JJTABSTRACT_DECLARATOR = 80;
  public int JJTABSTRACT_DECLARATOR_SUFFIX = 81;
  public int JJTTEMPLATE_HEAD = 82;
  public int JJTTEMPLATE_PARAMETER_LIST = 83;
  public int JJTTEMPLATE_PARAMETER = 84;
  public int JJTTEMPLATE_ID = 85;
  public int JJTTEMPLATE_ARGUMENT_LIST = 86;
  public int JJTTEMPLATE_ARGUMENT = 87;
  public int JJTEMPTY_STATEMENT = 88;
  public int JJTLABELED_STATEMENT = 89;
  public int JJTIF_STATEMENT = 90;
  public int JJTSWITCH_STATEMENT = 91;
  public int JJTSWITCH_LABEL = 92;
  public int JJTWHILE_STATEMENT = 93;
  public int JJTDO_STATEMENT = 94;
  public int JJTFOR_INIT = 95;
  public int JJTFOR_CONDITION = 96;
  public int JJTSTATEMENT_EXPRESSION_LIST = 97;
  public int JJTFOR_UPDATE = 98;
  public int JJTFOR_BLOCK = 99;
  public int JJTFOR_STATEMENT = 100;
  public int JJTGOTO_STATEMENT = 101;
  public int JJTCONTINUE_STATEMENT = 102;
  public int JJTBREAK_STATEMENT = 103;
  public int JJTRETURN_STATEMENT = 104;
  public int JJTTRY_BLOCK = 105;
  public int JJTHANDLER = 106;
  public int JJTEXCEPTION_DECLARATION = 107;
  public int JJTTHROW_STATEMENT = 108;
  public int JJTASSIGNMENT = 109;
  public int JJTEXPRESSION_ASSIGNMENT = 110;
  public int JJTASSIGNMENT_OPERATOR = 111;
  public int JJTASSIGNMENT_EXPRESSION_OPERATOR = 112;
  public int JJTQUESTIONMARK_EXPRESSION = 113;
  public int JJTCONSTANT_EXPRESSION = 114;
  public int JJTOR_NODE = 115;
  public int JJTAND_NODE = 116;
  public int JJTBITWISE_OR_NODE = 117;
  public int JJTBITWISE_XOR_NODE = 118;
  public int JJTBITWISE_AND_NODE = 119;
  public int JJTNEQ_NODE = 120;
  public int JJTEQ_NODE = 121;
  public int JJTLT_NODE = 122;
  public int JJTGT_NODE = 123;
  public int JJTLE_NODE = 124;
  public int JJTGE_NODE = 125;
  public int JJTLEFT_SHIFT_NODE = 126;
  public int JJTRIGHT_SHIFT_NODE = 127;
  public int JJTADD_NODE = 128;
  public int JJTSUBTRACT_NODE = 129;
  public int JJTMUL_NODE = 130;
  public int JJTDIV_NODE = 131;
  public int JJTMOD_NODE = 132;
  public int JJTPM_EXPRESSION = 133;
  public int JJTCAST_EXPRESSION = 134;
  public int JJTPREINCREMENT_NODE = 135;
  public int JJTPREDECREMENT_NODE = 136;
  public int JJTUNARY_EXPRESSION = 137;
  public int JJTSIZEOF_EXPRESSION = 138;
  public int JJTNEW_EXPRESSION = 139;
  public int JJTNEW_TYPE_ID = 140;
  public int JJTNEW_DECLARATOR = 141;
  public int JJTDIRECT_NEW_DECLARATOR = 142;
  public int JJTNEW_INITIALIZER = 143;
  public int JJTDELETE_EXPRESSION = 144;
  public int JJTDELETE_ARRAY_EXPRESSION = 145;
  public int JJTUNARY_OPERATOR = 146;
  public int JJTARGUMENTS = 147;
  public int JJTDEREFERENCING_OPERATOR = 148;
  public int JJTARRAYACCESS_EXPRESSION = 149;
  public int JJTPRIMARY_EXPRESSION = 150;
  public int JJTPOSTINCREMENT_NODE = 151;
  public int JJTPOSTDECREMENT_NODE = 152;
  public int JJTID_EXPRESSION = 153;
  public int JJTOPTOR_OVERLOADING = 154;
  public int JJTTHIS_NODE = 155;
  public int JJTARGUMENTS_LIST = 156;
  public int JJTCONSTANT = 157;
  public int JJTOPTOR = 158;
  public int JJTEXCEPTION_SPEC = 159;
  public int JJTEXCEPTION_LIST = 160;
  public int JJTOUTPUT_STREAM = 161;
  public int JJTSTANDART_MANIPULATOR = 162;
  public int JJTSC_MAP_TO_TARGET_DECLARATION = 163;
  public int JJTSC_MAP_TO_TARGET = 164;
  public int JJTNAMESPACE_DEFINITION = 165;
  public int JJTNAMED_NAMESPACE_DEFINITION = 166;
  public int JJTORIGINAL_NAMESPACE_DEFINITION = 167;
  public int JJTEXTENDED_NAMESPACE_DEFINITION = 168;
  public int JJTUNNAMED_NAMESPACE_DEFINITION = 169;
  public int JJTNAMESPACE_BODY = 170;
  public int JJTALIAS_NAMESPACE_DEFINITION = 171;
  public int JJTNAMESPACE_QUALIFIED_SPEC = 172;
  public int JJTUSING_DECLARATION = 173;
  public int JJTUSING_DIRECTIVE = 174;
  public int JJTCLASS_OR_NAMESPACE_NAME = 175;
  public int JJTCOMPLICATED_NAME_SPEC = 176;
  public int JJTNAMESPACE_NAME = 177;
  public int JJTORIGINAL_NAMESPACE_NAME = 178;
  public int JJTALIAS_NAMESPACE_NAME = 179;
  public int JJTNOT_QUALIFIED_ID = 180;
  public int JJTCLASS_NAME = 181;
  public int JJTCOMMENT = 182;


  public String[] jjtNodeName = {
    "translation_unit",
    "void",
    "preprocessor_directive",
    "external_declaration",
    "fzi_sim_directive",
    "sc_main_declaration",
    "block_statement",
    "block",
    "systemCRoutine",
    "dyn_process_creation_block_declaration",
    "sc_port_specifier",
    "m_s_protocol_declaration",
    "sc_slave",
    "sc_method",
    "sc_thread",
    "sc_report_macro",
    "sc_cthread",
    "sc_watching_list",
    "sc_watching",
    "sc_sensitive",
    "postfix_expression",
    "sc_notify",
    "function_definition",
    "linkage_specification",
    "declaration",
    "init_declarator_list",
    "type_modifiers",
    "declaration_specifiers",
    "type_specifier",
    "simple_type_specifier",
    "scope_override_lookahead",
    "scope_override",
    "qualified_id",
    "ptr_to_member",
    "qualified_type",
    "type_qualifier",
    "storage_class_specifier",
    "builtin_type_specifier",
    "init_declarator",
    "class_head",
    "class_specifier",
    "base_clause",
    "base_class_access_specifier",
    "base_specifier",
    "access_specifier",
    "bit_field_member_declaration",
    "member_declaration",
    "member_declarator_list",
    "member_declarator",
    "conversion_function_decl_or_def",
    "enum_specifier",
    "enumerator_list",
    "enumerator",
    "ptr_operator",
    "cv_qualifier",
    "declarator",
    "declarator_suffixes",
    "function_declarator_lookahead",
    "function_declarator",
    "dtor_ctor_decl_spec",
    "dtor_definition",
    "local_watching_block",
    "begin_block",
    "do_block",
    "escape_block",
    "ctor_definition",
    "sc_method_block",
    "sc_thread_block",
    "sc_cthread_block",
    "ctor_declarator_lookahead",
    "ctor_initializer",
    "superclass_init",
    "dtor_declarator",
    "simple_dtor_declarator",
    "parameter_list",
    "ellipsis_parameter",
    "parameter_declaration",
    "initializer",
    "array_initializer",
    "type_name",
    "abstract_declarator",
    "abstract_declarator_suffix",
    "template_head",
    "template_parameter_list",
    "template_parameter",
    "template_id",
    "template_argument_list",
    "template_argument",
    "empty_statement",
    "labeled_statement",
    "if_statement",
    "switch_statement",
    "switch_label",
    "while_statement",
    "do_statement",
    "for_init",
    "for_condition",
    "statement_expression_list",
    "for_update",
    "for_block",
    "for_statement",
    "goto_statement",
    "continue_statement",
    "break_statement",
    "return_statement",
    "try_block",
    "handler",
    "exception_declaration",
    "throw_statement",
    "assignment",
    "expression_assignment",
    "assignment_operator",
    "assignment_expression_operator",
    "questionmark_expression",
    "constant_expression",
    "or_node",
    "and_node",
    "bitwise_or_node",
    "bitwise_xor_node",
    "bitwise_and_node",
    "neq_node",
    "eq_node",
    "lt_node",
    "gt_node",
    "le_node",
    "ge_node",
    "left_shift_node",
    "right_shift_node",
    "add_node",
    "subtract_node",
    "mul_node",
    "div_node",
    "mod_node",
    "pm_expression",
    "cast_expression",
    "preincrement_node",
    "predecrement_node",
    "unary_expression",
    "sizeof_expression",
    "new_expression",
    "new_type_id",
    "new_declarator",
    "direct_new_declarator",
    "new_initializer",
    "delete_expression",
    "delete_array_expression",
    "unary_operator",
    "arguments",
    "dereferencing_operator",
    "arrayaccess_expression",
    "primary_expression",
    "postincrement_node",
    "postdecrement_node",
    "id_expression",
    "optor_overloading",
    "this_node",
    "arguments_list",
    "constant",
    "optor",
    "exception_spec",
    "exception_list",
    "output_stream",
    "standart_manipulator",
    "sc_map_to_target_declaration",
    "sc_map_to_target",
    "namespace_definition",
    "named_namespace_definition",
    "original_namespace_definition",
    "extended_namespace_definition",
    "unnamed_namespace_definition",
    "namespace_body",
    "alias_namespace_definition",
    "namespace_qualified_spec",
    "using_declaration",
    "using_directive",
    "class_or_namespace_name",
    "complicated_name_spec",
    "namespace_name",
    "original_namespace_name",
    "alias_namespace_name",
    "not_qualified_id",
    "class_name",
    "comment",
  };
}
/* JavaCC - OriginalChecksum=02e583db49c070d2e333aabee92ea3f4 (do not edit this line) */
